Description: Ubuntu webserver stack


Resources:

  appSecuritygroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupName: ex1_student3_sg1
        GroupDescription: "Allow all/tcp out and ssh/tcp, http/tcp in"
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: "22"
            ToPort: "22"
            CidrIp: 0.0.0.0/0
          - IpProtocol: tcp
            FromPort: "80"
            ToPort: "80"
            CidrIp: 0.0.0.0/0
        VpcId: vpc-b66b6ad1
        Tags:
          - Key: Name
            Value: !Sub "CloudFormation-${AWS::StackName}-AppSecurityGroup"


  Instance1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0773391ae604c49a4            #Ubuntu Server 16.04
      KeyName: lab_key_3
      SecurityGroupIds:
        - !Ref appSecuritygroup
      Tags:
        - Key: Name
          Value: "student3-EX1-INSTANCE1"
      UserData:
        Fn::Base64: !Sub |
           #!/bin/bash -xe
           apt update -y
           apt install -y apache2

  Instance2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0773391ae604c49a4            #Ubuntu Server 16.04
      KeyName: lab_key_3
      SecurityGroupIds:
        - !Ref appSecuritygroup
      Tags:
        - Key: Name
          Value: "student3-EX1-INSTANCE2"
      UserData:
        Fn::Base64: !Sub |
           #!/bin/bash -xe
           apt update -y
           apt install -y apache2


  lab3ELB:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      SecurityGroups:
        - !Ref appSecuritygroup
      Instances:
        - !Ref Instance1
        - !Ref Instance2
      Listeners:
        - LoadBalancerPort: '80'
          InstancePort: '80'
          Protocol: TCP
      Subnets:
        - subnet-4481bd0d
        - subnet-9587f0ce
        - subnet-1e260c79
      Tags:
        - Key: Name
          Value: !Sub "CloudFormation-${AWS::StackName}-ElasticLoadBalancer"
