Description: Ubuntu webserver stack

Resources:

  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0773391ae604c49a4            #Ubuntu Server 16.04
      KeyName: lab_key_2

  
